### ISSUE TITLE
The content of model file was generated wrong

### ISSUE THREAD

**Issue by hungntit** [DamienP33/express-mongoose-generator#11] opened 2017-06-07 10:58 UTC
```
mongoose-gen

Model Name : car
Available types : string, number, date, boolean, array, objectId
Field Name (press <return> to stop adding fields) : door
Field Type [string] : number
Field Name (press <return> to stop adding fields) : color
Field Type [string] :
Field Name (press <return> to stop adding fields) : owner
Field Type [string] : objectid
Invalid Argument : Field type is not allowed
Field Type [string] : objectId
Reference (model name referred by the objectId field) : User
Field Name (press <return> to stop adding fields) :
Generate Rest (yes/no) ? [yes] : yes
Files tree generation grouped by Type or by Module (t/m) ? [t] : m
	create: ./car
	create: ./car/carRoutes.js
	create: ./car/carModel.js
	create: ./car/carController.js
ken@Ken:~/working/nodejs/tut2$ cat car/carModel.js
var mongoose = require('mongoose');
var Schema   = mongoose.Schema;

}); carS}owner' ref: 'User'a.Types.ObjectId,
```

**Comment by DamienP33** [comment] 2017-06-07 12:54
This error is caused by the line separator Windows (see issue #8 ).
I fixed in the 3.0.3 version.

**Closed by DamienP33** 2017-06-07 12:54 UTC
Labels: bug
